/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'stefano' at '02/11/13 10.49' with Gradle 1.8
 *
 * @author stefano, @date 02/11/13 10.49
 */
public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
