import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'stefano' at '02/11/13 10.49' with Gradle 1.8
 *
 * @author stefano, @date 02/11/13 10.49
 */
public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'",
				classUnderTest.someLibraryMethod());
	}
}
